In [1]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
import numpy as np
from langchain_core.embeddings import Embeddings
from sklearn.feature_extraction.text import TfidfVectorizer
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

WARNING:tensorflow:From C:\Users\Arup sarkar\.conda\envs\condaenv3\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
from dotenv import load_dotenv
load_dotenv()

False

In [3]:
import pandas as pd

books = pd.read_csv("books_Cleaned.csv")

In [4]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [5]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: object

In [6]:
books["tagged_description"].to_csv("tagged_description.txt", index=False, header=False, sep="\n")

In [7]:
raw_documents = TextLoader("tagged_description.txt", encoding="utf-8").load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1168, which is longer than the specified 1000
Created a chunk of size 1214, which is longer than the specified 1000
Created a chunk of size 1088, which is longer than the specified 1000
Created a chunk of size 1189, which is longer than the specified 1000
Created a chunk of size 1267, which is longer than the specified 1000
Created a chunk of size 2010, which is longer than the specified 1000
Created a chunk of size 1225, which is longer than the specified 1000
Created a chunk of size 1184, which is longer than the specified 1000
Created a chunk of size 1214, which is longer than the specified 1000
Created a chunk of size 1191, which is longer than the specified 1000
Created a chunk of size 1057, which is longer than the specified 1000
Created a chunk of size 1270, which is longer than the specified 1000
Created a chunk of size 1635, which is longer than the specified 1000
Created a chunk of size 1132, which is longer than the specified 1000
Created a chunk of size 1325, which is longer than the specified 1000
Created a chunk of size 1119, which is longer than the specified 1000
Created a chunk of size 1195, which is longer than the specified 1000
Created a chunk of size 2012, which is longer than the specified 1000
Created a chunk of size 1286, which is longer than the specified 1000
Created a chunk of size 1231, which is longer than the specified 1000
Created a chunk of size 1242, which is longer than the specified 1000
Created a chunk of size 1126, which is longer than the specified 1000
Created a chunk of size 1073, which is longer than the specified 1000
Created a chunk of size 1318, which is longer than the specified 1000
Created a chunk of size 2834, which is longer than the specified 1000
Created a chunk of size 1141, which is longer than the specified 1000
Created a chunk of size 1004, which is longer than the specified 1000
Created a chunk of size 2510, which is longer than the specified 1000
Created a chunk of size 1422, which is longer than the specified 1000
Created a chunk of size 1083, which is longer than the specified 1000
Created a chunk of size 1144, which is longer than the specified 1000
Created a chunk of size 1268, which is longer than the specified 1000
Created a chunk of size 1086, which is longer than the specified 1000
Created a chunk of size 1812, which is longer than the specified 1000
Created a chunk of size 1830, which is longer than the specified 1000
Created a chunk of size 1064, which is longer than the specified 1000
Created a chunk of size 1180, which is longer than the specified 1000
Created a chunk of size 1284, which is longer than the specified 1000
Created a chunk of size 1642, which is longer than the specified 1000
Created a chunk of size 1930, which is longer than the specified 1000
Created a chunk of size 2008, which is longer than the specified 1000
Created a chunk of size 2285, which is longer than the specified 1000
Created a chunk of size 1003, which is longer than the specified 1000
Created a chunk of size 1142, which is longer than the specified 1000
Created a chunk of size 1143, which is longer than the specified 1000
Created a chunk of size 1086, which is longer than the specified 1000
Created a chunk of size 1483, which is longer than the specified 1000
Created a chunk of size 1135, which is longer than the specified 1000
Created a chunk of size 1032, which is longer than the specified 1000
Created a chunk of size 1015, which is longer than the specified 1000
Created a chunk of size 1088, which is longer than the specified 1000
Created a chunk of size 1912, which is longer than the specified 1000
Created a chunk of size 2616, which is longer than the specified 1000
Created a chunk of size 1580, which is longer than the specified 1000
Created a chunk of size 1530, which is longer than the specified 1000
Created a chunk of size 2030, which is longer than the specified 1000
Created a chunk of size 1619, which is longer than the specified 1000
Created a chunk of size 1189, which is longer than the specified 1000
Created a chunk of size 1282, which is longer than the specified 1000
Created a chunk of size 1268, which is longer than the specified 1000
Created a chunk of size 1277, which is longer than the specified 1000
Created a chunk of size 1056, which is longer than the specified 1000
Created a chunk of size 1163, which is longer than the specified 1000
Created a chunk of size 1058, which is longer than the specified 1000
Created a chunk of size 1084, which is longer than the specified 1000
Created a chunk of size 2762, which is longer than the specified 1000
Created a chunk of size 1033, which is longer than the specified 1000
Created a chunk of size 1010, which is longer than the specified 1000
Created a chunk of size 1064, which is longer than the specified 1000
Created a chunk of size 1224, which is longer than the specified 1000
Created a chunk of size 1805, which is longer than the specified 1000
Created a chunk of size 1017, which is longer than the specified 1000
Created a chunk of size 1268, which is longer than the specified 1000
Created a chunk of size 1771, which is longer than the specified 1000
Created a chunk of size 1270, which is longer than the specified 1000
Created a chunk of size 1019, which is longer than the specified 1000
Created a chunk of size 1177, which is longer than the specified 1000
Created a chunk of size 1715, which is longer than the specified 1000
Created a chunk of size 1681, which is longer than the specified 1000
Created a chunk of size 1128, which is longer than the specified 1000
Created a chunk of size 2005, which is longer than the specified 1000
Created a chunk of size 1171, which is longer than the specified 1000
Created a chunk of size 2141, which is longer than the specified 1000
Created a chunk of size 1322, which is longer than the specified 1000
Created a chunk of size 1112, which is longer than the specified 1000
Created a chunk of size 1316, which is longer than the specified 1000
Created a chunk of size 1121, which is longer than the specified 1000
Created a chunk of size 1018, which is longer than the specified 1000
Created a chunk of size 1007, which is longer than the specified 1000
Created a chunk of size 1057, which is longer than the specified 1000
Created a chunk of size 1255, which is longer than the specified 1000
Created a chunk of size 1098, which is longer than the specified 1000
Created a chunk of size 1143, which is longer than the specified 1000
Created a chunk of size 1550, which is longer than the specified 1000
Created a chunk of size 1652, which is longer than the specified 1000
Created a chunk of size 1495, which is longer than the specified 1000
Created a chunk of size 1277, which is longer than the specified 1000
Created a chunk of size 1046, which is longer than the specified 1000
Created a chunk of size 1666, which is longer than the specified 1000
Created a chunk of size 1616, which is longer than the specified 1000
Created a chunk of size 1095, which is longer than the specified 1000
Created a chunk of size 1597, which is longer than the specified 1000
Created a chunk of size 1960, which is longer than the specified 1000
Created a chunk of size 1708, which is longer than the specified 1000
Created a chunk of size 1947, which is longer than the specified 1000
Created a chunk of size 1027, which is longer than the specified 1000
Created a chunk of size 1807, which is longer than the specified 1000
Created a chunk of size 1518, which is longer than the specified 1000
Created a chunk of size 1087, which is longer than the specified 1000
Created a chunk of size 1093, which is longer than the specified 1000
Created a chunk of size 1167, which is longer than the specified 1000
Created a chunk of size 1259, which is longer than the specified 1000
Created a chunk of size 1480, which is longer than the specified 1000
Created a chunk of size 1037, which is longer than the specified 1000
Created a chunk of size 1085, which is longer than the specified 1000
Created a chunk of size 1443, which is longer than the specified 1000
Created a chunk of size 1266, which is longer than the specified 1000
Created a chunk of size 1144, which is longer than the specified 1000
Created a chunk of size 1369, which is longer than the specified 1000
Created a chunk of size 1622, which is longer than the specified 1000
Created a chunk of size 1165, which is longer than the specified 1000
Created a chunk of size 1176, which is longer than the specified 1000
Created a chunk of size 1179, which is longer than the specified 1000
Created a chunk of size 1009, which is longer than the specified 1000
Created a chunk of size 1022, which is longer than the specified 1000
Created a chunk of size 1357, which is longer than the specified 1000
Created a chunk of size 1172, which is longer than the specified 1000
Created a chunk of size 1394, which is longer than the specified 1000
Created a chunk of size 1216, which is longer than the specified 1000
Created a chunk of size 2209, which is longer than the specified 1000
Created a chunk of size 1371, which is longer than the specified 1000
Created a chunk of size 2877, which is longer than the specified 1000
Created a chunk of size 1279, which is longer than the specified 1000
Created a chunk of size 1714, which is longer than the specified 1000
Created a chunk of size 1638, which is longer than the specified 1000
Created a chunk of size 2398, which is longer than the specified 1000
Created a chunk of size 2120, which is longer than the specified 1000
Created a chunk of size 1488, which is longer than the specified 1000
Created a chunk of size 1691, which is longer than the specified 1000
Created a chunk of size 1418, which is longer than the specified 1000
Created a chunk of size 1173, which is longer than the specified 1000
Created a chunk of size 1359, which is longer than the specified 1000
Created a chunk of size 2181, which is longer than the specified 1000
Created a chunk of size 1093, which is longer than the specified 1000
Created a chunk of size 2171, which is longer than the specified 1000
Created a chunk of size 1454, which is longer than the specified 1000
Created a chunk of size 1454, which is longer than the specified 1000
Created a chunk of size 1973, which is longer than the specified 1000
Created a chunk of size 1987, which is longer than the specified 1000
Created a chunk of size 1648, which is longer than the specified 1000
Created a chunk of size 2723, which is longer than the specified 1000
Created a chunk of size 1632, which is longer than the specified 1000
Created a chunk of size 1284, which is longer than the specified 1000
Created a chunk of size 1484, which is longer than the specified 1000
Created a chunk of size 1049, which is longer than the specified 1000
Created a chunk of size 1003, which is longer than the specified 1000
Created a chunk of size 1150, which is longer than the specified 1000
Created a chunk of size 1216, which is longer than the specified 1000
Created a chunk of size 1032, which is longer than the specified 1000
Created a chunk of size 2456, which is longer than the specified 1000
Created a chunk of size 1349, which is longer than the specified 1000
Created a chunk of size 1271, which is longer than the specified 1000
Created a chunk of size 1117, which is longer than the specified 1000
Created a chunk of size 1548, which is longer than the specified 1000
Created a chunk of size 1201, which is longer than the specified 1000
Created a chunk of size 1160, which is longer than the specified 1000
Created a chunk of size 1149, which is longer than the specified 1000
Created a chunk of size 1024, which is longer than the specified 1000
Created a chunk of size 1774, which is longer than the specified 1000
Created a chunk of size 1165, which is longer than the specified 1000
Created a chunk of size 1009, which is longer than the specified 1000
Created a chunk of size 1017, which is longer than the specified 1000
Created a chunk of size 1323, which is longer than the specified 1000
Created a chunk of size 1213, which is longer than the specified 1000
Created a chunk of size 1123, which is longer than the specified 1000
Created a chunk of size 1598, which is longer than the specified 1000
Created a chunk of size 1963, which is longer than the specified 1000
Created a chunk of size 2450, which is longer than the specified 1000
Created a chunk of size 1796, which is longer than the specified 1000
Created a chunk of size 1568, which is longer than the specified 1000
Created a chunk of size 1219, which is longer than the specified 1000
Created a chunk of size 1380, which is longer than the specified 1000
Created a chunk of size 1452, which is longer than the specified 1000
Created a chunk of size 1102, which is longer than the specified 1000
Created a chunk of size 1298, which is longer than the specified 1000
Created a chunk of size 1761, which is longer than the specified 1000
Created a chunk of size 1004, which is longer than the specified 1000
Created a chunk of size 1022, which is longer than the specified 1000
Created a chunk of size 1064, which is longer than the specified 1000
Created a chunk of size 1009, which is longer than the specified 1000
Created a chunk of size 1064, which is longer than the specified 1000
Created a chunk of size 1629, which is longer than the specified 1000
Created a chunk of size 1593, which is longer than the specified 1000
Created a chunk of size 1587, which is longer than the specified 1000
Created a chunk of size 1259, which is longer than the specified 1000
Created a chunk of size 1128, which is longer than the specified 1000
Created a chunk of size 1105, which is longer than the specified 1000
Created a chunk of size 1080, which is longer than the specified 1000
Created a chunk of size 1533, which is longer than the specified 1000
Created a chunk of size 1202, which is longer than the specified 1000
Created a chunk of size 1093, which is longer than the specified 1000
Created a chunk of size 1247, which is longer than the specified 1000
Created a chunk of size 1056, which is longer than the specified 1000
Created a chunk of size 1211, which is longer than the specified 1000
Created a chunk of size 1011, which is longer than the specified 1000
Created a chunk of size 1352, which is longer than the specified 1000
Created a chunk of size 1412, which is longer than the specified 1000
Created a chunk of size 1023, which is longer than the specified 1000
Created a chunk of size 1216, which is longer than the specified 1000
Created a chunk of size 1131, which is longer than the specified 1000
Created a chunk of size 1197, which is longer than the specified 1000
Created a chunk of size 1891, which is longer than the specified 1000
Created a chunk of size 3168, which is longer than the specified 1000
Created a chunk of size 1532, which is longer than the specified 1000
Created a chunk of size 1588, which is longer than the specified 1000
Created a chunk of size 1609, which is longer than the specified 1000
Created a chunk of size 1623, which is longer than the specified 1000
Created a chunk of size 1419, which is longer than the specified 1000
Created a chunk of size 1114, which is longer than the specified 1000
Created a chunk of size 1128, which is longer than the specified 1000
Created a chunk of size 1036, which is longer than the specified 1000
Created a chunk of size 1139, which is longer than the specified 1000
Created a chunk of size 1178, which is longer than the specified 1000
Created a chunk of size 1048, which is longer than the specified 1000
Created a chunk of size 1211, which is longer than the specified 1000
Created a chunk of size 1169, which is longer than the specified 1000
Created a chunk of size 2034, which is longer than the specified 1000
Created a chunk of size 1115, which is longer than the specified 1000
Created a chunk of size 1436, which is longer than the specified 1000
Created a chunk of size 1113, which is longer than the specified 1000
Created a chunk of size 1062, which is longer than the specified 1000
Created a chunk of size 1471, which is longer than the specified 1000
Created a chunk of size 1436, which is longer than the specified 1000
Created a chunk of size 1330, which is longer than the specified 1000
Created a chunk of size 1721, which is longer than the specified 1000
Created a chunk of size 1530, which is longer than the specified 1000
Created a chunk of size 1651, which is longer than the specified 1000
Created a chunk of size 1579, which is longer than the specified 1000
Created a chunk of size 1646, which is longer than the specified 1000
Created a chunk of size 1687, which is longer than the specified 1000
Created a chunk of size 2031, which is longer than the specified 1000
Created a chunk of size 1107, which is longer than the specified 1000
Created a chunk of size 1049, which is longer than the specified 1000
Created a chunk of size 1118, which is longer than the specified 1000
Created a chunk of size 1089, which is longer than the specified 1000
Created a chunk of size 1103, which is longer than the specified 1000
Created a chunk of size 1130, which is longer than the specified 1000
Created a chunk of size 1338, which is longer than the specified 1000
Created a chunk of size 1080, which is longer than the specified 1000
Created a chunk of size 1163, which is longer than the specified 1000
Created a chunk of size 1003, which is longer than the specified 1000
Created a chunk of size 1085, which is longer than the specified 1000
Created a chunk of size 1003, which is longer than the specified 1000
Created a chunk of size 1226, which is longer than the specified 1000
Created a chunk of size 1235, which is longer than the specified 1000
Created a chunk of size 2940, which is longer than the specified 1000
Created a chunk of size 1118, which is longer than the specified 1000
Created a chunk of size 1490, which is longer than the specified 1000
Created a chunk of size 1157, which is longer than the specified 1000
Created a chunk of size 1208, which is longer than the specified 1000
Created a chunk of size 1489, which is longer than the specified 1000
Created a chunk of size 1086, which is longer than the specified 1000
Created a chunk of size 1802, which is longer than the specified 1000
Created a chunk of size 1595, which is longer than the specified 1000
Created a chunk of size 1030, which is longer than the specified 1000
Created a chunk of size 1361, which is longer than the specified 1000
Created a chunk of size 1643, which is longer than the specified 1000
Created a chunk of size 1382, which is longer than the specified 1000
Created a chunk of size 1763, which is longer than the specified 1000
Created a chunk of size 1971, which is longer than the specified 1000
Created a chunk of size 1240, which is longer than the specified 1000
Created a chunk of size 1119, which is longer than the specified 1000
Created a chunk of size 1051, which is longer than the specified 1000
Created a chunk of size 1006, which is longer than the specified 1000
Created a chunk of size 1119, which is longer than the specified 1000
Created a chunk of size 1127, which is longer than the specified 1000
Created a chunk of size 1037, which is longer than the specified 1000
Created a chunk of size 1280, which is longer than the specified 1000
Created a chunk of size 1475, which is longer than the specified 1000
Created a chunk of size 1268, which is longer than the specified 1000
Created a chunk of size 1219, which is longer than the specified 1000
Created a chunk of size 1003, which is longer than the specified 1000
Created a chunk of size 1045, which is longer than the specified 1000
Created a chunk of size 1052, which is longer than the specified 1000
Created a chunk of size 1017, which is longer than the specified 1000

In [8]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

In [9]:
"""
Initial TFIDF EMBEDDING
"""


# class TfidfEmbeddings(Embeddings):
#     def __init__(self):
#         self.vectorizer = TfidfVectorizer(
#             max_features=5000,
#             stop_words="english"
#         )
#         self._fit_done = False
#
#     def fit(self, texts):
#         self.vectorizer.fit(texts)
#         self._fit_done = True
#         return self
#
#     def embed_documents(self, texts):
#         if not self._fit_done:
#             self.fit(texts)
#         matrix = self.vectorizer.transform(texts)
#         return matrix.toarray().astype(np.float32).tolist()
#
#     def embed_query(self, text):
#         if not self._fit_done:
#             raise ValueError("Embedding model must be fit on documents before querying.")
#         vector = self.vectorizer.transform([text])
#         return vector.toarray().astype(np.float32)[0].tolist()
#
#
# # Build a local embedding model from your documents
# texts = [doc.page_content for doc in documents]
# embedding_model = TfidfEmbeddings().fit(texts)
#
# db_books = Chroma.from_documents(
#     documents=documents,
#     embedding=embedding_model
# )
#

'\nInitial TFIDF EMBEDDING\n'

In [10]:
"""
OPENAI EMBEDDING (NEED TO USE API KEY)
"""
#db_books = Chroma.from_documents(
#    documents=documents,
#    embedding=OpenAIEmbeddings()
#)

'\nOPENAI EMBEDDING (NEED TO USE API KEY)\n'

In [11]:
embedding_model = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

db_books = Chroma.from_documents(
    documents=documents,
    embedding=embedding_model
)

C:\Users\Arup sarkar\.conda\envs\condaenv3\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [12]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k=10)

In [13]:
docs

[Document(id='75be3ef6-2e20-4cc4-9bd5-ff8892a869fb', metadata={'source': 'tagged_description.txt'}, page_content="9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.\n9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."),
 Document(id='1371ddcb-d03e-48b5-b4d5-d4e5484ca8b8', metadata={'source': 'tagged_description.txt'}, page_content="9780064402453 ‘Racso, a brash and boastful little rodent, is making his way to Thorn Valley, determined to learn how to read and write and become a hero. His bragging and lies get him off to a bad start, but a crisis gives him the opportunity to prove his mettle. A worthy successor [to Mrs. Frisby and the Rats of NIMH, a Newbery Medal winner by the author's father].' 'BL. 1986 Children's Editors' Choices (BL) Children's Choices for 1987 (IRA/CBC) Notable 1986 Childrens' Trade Books in Social Studies (NCSS/CBC) 1986 Children's Books (NY Public Library) Best Science Fiction/Fantasy 1986 (VOYA)"),
 Document(id='86cad7b6-264f-4a86-a789-14eba5b635f1', metadata={'source': 'tagged_description.txt'}, page_content="9780142402931 A young girl from an advanced civilization is sent as an observer to a planet whose people have not yet learned to control their use of atomic power.\n9780142403013 After dreaming that they must leave their isolated home of Riverworld, Kyreol and Terje travel beyond what they believe to be end of the world, where they discover new planets and new ways of life. Reissue.\n9780142403204 Sixteen original stories showcase some of the genre's most admired authors, including multiple award-winners Diana Wynne Jones, Garth Nix, Lloyd Alexander, Nancy Farmer, and Meredith Ann Pierce. An ALA Best Book for Young Adults. Reprint.\n9780142404201 Each of five children lucky enough to discover an entry ticket into Mr. Willy Wonka's mysterious chocolate factory takes advantage of the situation in his own way."),
 Document(id='c83c80c5-0cf0-4c8a-8c00-9bd1e68644cf', metadata={'source': 'tagged_description.txt'}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects.\n9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='e1cff77e-7256-4374-96c9-be40eb36444e', metadata={'source': 'tagged_description.txt'}, page_content='"9781593851170 ""Comprehensive and up to date, this tightly edited volume belongs on the desks of researchers and students in developmental psychology, comparative psychology, animal behavior, and evolutionary psychology, and will also be of interest to anthropologists. It is a richly informative text for advanced undergraduate- and graduate-level courses.""--BOOK JACKET."'),
 Document(id='421ceb30-3e29-4c47-bb97-2de5fdad1b58', metadata={'source': 'tagged_description.txt'}, page_content="9780374517885 The Noble laureate has selected nearly 150 of his acclaimed stories, from his eight previous collections, offering abundant evidence of his mastery of the genre\n9780374522599 The Control of Nature is John McPhee's bestselling account of places where people are locked in combat with nature. Taking us deep into these contested territories, McPhee details the strageties and tactics through which people attempt to control nature. Most striking is his depiction of the main contestants: nature in complex and awesome guises, and those attempting to wrest control from her - stubborn, sometimes foolhardy, more often ingenious, and always arresting characters.\n9780374522872 An account of a kayak and canoe journey through the Brooks Range wilderness, impressions of urban life and political activity, and portraits of people in the bush make up a study of contemporary Alaska"),
 Document(id='b1e9b1b3-6c02-4cb3-b66f-f7f36aa7c15b', metadata={'source': 'tagged_description.txt'}, page_content="9780064403870 When Margaret and her younger brother, Artie, get lost in the woods on a family camping trip, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat's community, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do, they must protect the rats who have helped them. Everything depends on their silence... but it's hard to evade questions forever. Children's Choices for 1991 (IRA/CBC)VOYA's Best Science Fiction, Fantasy, and Horror 1990Parenting Honorable Mention, Reading Magic Award"),
 Document(id='f9596339-c1fa-4ab1-a52e-20d0b55069d9', metadata={'source': 'tagged_description.txt'}, page_content="9780941807555 THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wonderful resource for parents looking to introduce their children to the wisdom and beauty of Christian faith. Illustrated with early twentieth-century art from artists such as Jessie Wilcox Smith, Ellen H. Clapsaddle, and Maud and Miska Petersham, this Little Big Book presents selected bible stories, parables, and verses; poems and prayers; excerpts and fables; songs and hymns; and activities - all collected in one delightful volume. A celebration of God's enduring message of love, GOD'S CHILDREN is sure to provide an endless wellspring of inspiration and hope."),
 Document(id='5df0dbab-947a-401e-a6c8-6fab3e8fa52e', metadata={'source': 'tagged_description.txt'}, page_content="9780393930139 Long the standard teaching anthology, the landmark Norton Anthology of Literature by Women has introduced generations of readers to the rich variety of women's writing in English.\n9780393959055 The classic chronicle of a communion with nature at Walden Pond offers a message of living simply and in harmony with nature, and Thoreau champions the belief that people of conscience are at liberty to follow their own opinions."),
 Document(id='35e81bdb-5d85-4971-8f27-40bdf8b1276a', metadata={'source': 'tagged_description.txt'}, page_content="9780064406925 The Little House books tell the story of a little pioneer girl and her family as they traveled by covered wagon across the Midwest. Laura Ingalls Wilder's classic books, illustrated with Garth Williams' timeless artwork, have been cherished by millions of readers ever since they were first published over sixty years ago. This My First Little House Book introduces Almanzo Wilder, the young boy from Farmer Boy who would one day marry Laura Ingalls. In Winter on the Farm, Almanzo goes through his afternoon barn chores, and then sits down to eat a hearty farm supper with his family. In this first book about Almanzo, young readers are able to share in the warmth and joy of another Little House family and celebrate new Little House adventures. Winter on the Farm is the first in an ongoing series about Laura’s beloved farmer boy.")]

In [14]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [15]:
def retrieve_semantic_recommendations(query: str, top_k: int = 50) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k=50)

    books_list = []

    for doc in recs:
        lines = doc.page_content.strip('"').split("\n")
        for line in lines:
            line = line.strip()
            if line:
                try:
                    isbn = int(line.split()[0])
                    books_list.append(isbn)
                except:
                    continue

    return books[books["isbn13"].isin(books_list)].head(top_k)

In [16]:
retrieve_semantic_recommendations("A book to teach children about nature",top_k=50)

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
30,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,Ocean Star Express,9780006646006 Joe and his parents are enjoying...
59,9780007151240,0007151241,The Family Way,Tony Parsons,Parenthood,http://books.google.com/books/content?id=dJEIx...,It should be the most natural thing in the wor...,2005.0,3.51,400.0,2095.0,The Family Way,9780007151240 It should be the most natural th...
60,9780007151677,0007151675,Endless Night,Agatha Christie,FICTION,http://books.google.com/books/content?id=kY1wu...,Gipsy S Acre Was A Truly Beautiful Upland Site...,2002.0,3.77,303.0,12740.0,Endless Night,9780007151677 Gipsy S Acre Was A Truly Beautif...
61,9780007153589,0007153589,How to be Alone,Jonathan Franzen,Literary Collections,http://books.google.com/books/content?id=ozVWa...,'The Harper's Essay' is reprinted in this volu...,2004.0,3.60,306.0,327.0,How to be Alone,9780007153589 'The Harper's Essay' is reprinte...
383,9780061144899,0061144894,When the Heart Waits,Sue Monk Kidd,Religion,http://books.google.com/books/content?id=JlP91...,From the Bestselling Author of The Secret Life...,2006.0,4.17,240.0,2141.0,When the Heart Waits: Spiritual Direction for ...,9780061144899 From the Bestselling Author of T...
392,9780061208492,0061208493,The Complete C. S. Lewis Signature Classics,C. S. Lewis,Religion,http://books.google.com/books/content?id=JaC0_...,Seven Spiritual Masterworks by C. S. Lewis Thi...,2007.0,4.61,746.0,873.0,The Complete C. S. Lewis Signature Classics,9780061208492 Seven Spiritual Masterworks by C...
393,9780061238239,0061238236,The End of Days,Zecharia Sitchin,History,http://books.google.com/books/content?id=EIBlj...,A conclusion to the Earth Chronicles series br...,2007.0,4.06,336.0,470.0,The End of Days: Armageddon and Prophecies of ...,9780061238239 A conclusion to the Earth Chroni...
404,9780064402453,0064402452,Racso and the Rats of NIMH,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=MgoNv...,"‘Racso, a brash and boastful little rodent, is...",1988.0,3.76,288.0,3231.0,Racso and the Rats of NIMH,"9780064402453 ‘Racso, a brash and boastful lit..."
406,9780064403870,0064403874,"R-T, Margaret, and the Rats of NIMH",Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=WTHHH...,"When Margaret and her younger brother, Artie, ...",1991.0,3.52,272.0,631.0,"R-T, Margaret, and the Rats of NIMH",9780064403870 When Margaret and her younger br...
407,9780064404419,0064404412,The Rainbow People,Laurence Yep,Juvenile Fiction,http://books.google.com/books/content?id=5AHwq...,"""Culled from 69 stories collected in a [1930s]...",1992.0,3.75,208.0,202.0,The Rainbow People,"9780064404419 ""Culled from 69 stories collecte..."
416,9780064406925,006440692X,Winter on the Farm,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=IvlKH...,The Little House books tell the story of a lit...,1997.0,4.13,32.0,400.0,Winter on the Farm,9780064406925 The Little House books tell the ...
427,9780064434874,0064434877,Christmas in the Big Woods,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=FT1Yp...,"Long ago, a little girl named Laura Ingalls li...",1997.0,4.19,32.0,2062.0,Christmas in the Big Woods,"9780064434874 Long ago, a little girl named La..."
428,9780064434942,006443494X,A Little House Birthday,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=fyfDR...,Join the Ingalls family as they celebrate litt...,1998.0,4.13,40.0,444.0,A Little House Birthday,9780064434942 Join the Ingalls family as they ...
429,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDW...,Even the youngest child can enjoy a special ad...,1999.0,4.17,32.0,302.0,The Deer in the Wood,9780064434980 Even the youngest child can enjo...
436,9780064471961,0064471969,Shade's Children (rack),Garth Nix,Juvenile Fiction,http://books.google.com/books/content?id=_jlgl...,The Key to Survival Rests in the Hands of Shad...,1998.0,3.90,345.0,10368.0,Shade's Children (rack),9780064471961 The Key to Survival Rests in the...
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,The Sense of Wonder,9780067575208 First published more than three ...
799,9780142003343,0142003344,The Blank Slate,Steven Pinker,Psychology,http://books.google.com/books/content?id=7rJ5g...,In a study of the nature versus nurture debate...,2003.0,4.08,528.0,17851.0,The Blank Slate: The Modern Denial of Human Na...,9780142003343 In a study of the nature versus ...
800,9780142003442,0142003441,Good Poems,Garrison Keillor,Poetry,http://books.google.com/books/content?id=fqmLD...,The popular radio show host showcases some of ...,2003.0,4.18,476.0,5977.0,Good Poems,9780142003442 The popular radio show host show...
801,9780142003565,0142003565,The Classic Ten,Nancy MacDonell Smith;Nancy MacDonell,Design,http://books.google.com/books/content?id=MioOc...,"Discusses the origins, history, and social sig...",2003.0,3.43,224.0,108.0,The Classic Ten: The True Story of the Little ...,"9780142003565 Discusses the origins, history, ..."
802,9780142003718,0142003719,I Should be Extremely Happy in Your Company,Brian Hall,Fiction,http://books.google.com/books/content?id=UqL39...,A fictionalized account based on the Lewis and...,2003.0,3.37,432.0,325.0,I Should be Extremely Happy in Your Company: A...,9780142003718 A fictionalized account based on...
816,9780142402931,0142402931,The Far Side of Evil,Sylvia Engdahl,Juvenile Fiction,http://books.google.com/books/content?id=7nijj...,A young girl from an advanced civilization is ...,2005.0,3.98,324.0,57.0,The Far Side of Evil,9780142402931 A young girl from an advanced ci...
817,9780142403013,0142403016,Moon-Flash,Patricia A. McKillip,Juvenile Fiction,http://books.google.com/books/content?id=wS-Xh...,After dreaming that they must leave their isol...,2005.0,3.73,304.0,340.0,Moon-Flash,9780142403013 After dreaming that they must le...
818,9780142403204,0142403202,Firebirds,Sharyn November,Juvenile Fiction,http://books.google.com/books/content?id=hL-gA...,Sixteen original stories showcase some of the ...,2005.0,3.96,432.0,3374.0,Firebirds: An Anthology of Original Fantasy an...,9780142403204 Sixteen original stories showcas...
819,9780142404201,0142404209,Charlie and the Chocolate Factory,Roald Dahl,Juvenile Fiction,http://books.google.com/books/content?id=X73lH...,Each of five children lucky enough to discover...,2005.0,3.86,40.0,12.0,Charlie and the Chocolate Factory,9780142404201 Each of five children lucky enou...
990,9780192854520,0192854526,Augustine: A Very Short Introduction,Henry Chadwick,Biography & Autobiography,http://books.google.com/books/content?id=QnrRB...,"Very Short Introductions offer stimulating, ac...",2001.0,3.74,144.0,219.0,Augustine: A Very Short Introduction,9780192854520 Very Short Introductions offer s...
991,9780192862099,019286209X,The Origins of Life,John Maynard Smith;Eörs Szathmáry,Science,http://books.google.com/books/content?id=nHDbB...,'I can recommend this book as a thoroughly int...,2000.0,4.11,192.0,41.0,The Origins of Life: From the Birth of Life to...,9780192862099 'I can recommend this book as a ...
1060,9780231054751,0231054750,Genetics and the Origin of Species,Theodosius Dobzhansky,Science,http://books.google.com/books/content?id=s7igy...,Featuring an introduction by Stephen Jay Gould...,1982.0,4.15,364.0,24.0,Genetics and the Origin of Species,9780231054751 Featuring an introduction by Ste...
1448,9780345345066,0345345061,The Tolkien Reader,J. R. R. Tolkien,Fiction,http://books.google.com/books/content?id=bhEdP...,"A fantastical anthology of short fiction, poet...",1986.0,3.99,272.0,4092.0,The Tolkien Reader,9780345345066 A fantastical anthology of short...
1449,9780345346292,0345346297,The Dragons of Eden,Carl Sagan,Nature,http://books.google.com/books/content?id=Nmkoz...,The well-known astronomer and astrobiologist s...,1977.0,4.17,271.0,14974.0,The Dragons of Eden: Speculations on the Evolu...,9780345346292 The well-known astronomer and as...
1639,9780374422080,0374422087,Everything on a Waffle,Polly Horvath,Juvenile Fiction,http://books.google.com/books/content?id=NimVJ...,This Newbery Honor Book tells the story of 11 ...,2004.0,3.71,150.0,9631.0,Everything on a Waffle,9780374422080 This Newbery Honor Book tells th...
1641,9780374517885,0374517886,Sammlung,Isaac Bashevis Singer,Fiction,http://books.google.com/books/content?id=B0_ws...,The Noble laureate has selected nearly 150 of ...,1982.0,4.37,624.0,1603.0,Sammlung,9780374517885 The Noble laureate has selected ...
1642,9780374522599,0374522596,The Control of Nature,John McPhee,Nature,http://books.google.com/books/content?id=p1qKQ...,The Control of Nature is John McPhee's bestsel...,1990.0,4.24,288.0,3365.0,The Control of Nature,9780374522599 The Control of Nature is John Mc...
1643,9780374522872,0374522871,Coming Into the Country,John McPhee,Nature,http://books.google.com/books/content?id=ds3uJ...,An account of a kayak and canoe journey throug...,1991.0,4.22,448.0,5452.0,Coming Into the Country,9780374522872 An account of a kayak and canoe ...
1751,9780380016365,0380016362,Laura,Donald Zochert,Biography & Autobiography,http://books.google.com/books/content?id=jqaFl...,"centerCourage, Adventure, Steadfast Love From ...",1977.0,4.11,241.0,5514.0,Laura: The Life of Laura Ingalls Wilder,"9780380016365 centerCourage, Adventure, Steadf..."
1752,9780380620005,0380620006,Boy Who Turned Into a TV Set,Stephen Manes,Juvenile Fiction,http://books.google.com/books/content?id=7geB7...,Although his mother warns him that if he conti...,1983.0,4.00,10.0,8.0,Boy Who Turned Into a TV Set,9780380620005 Although his mother warns him th...
1878,9780385732338,0385732333,Cuba 15,Nancy Osa,Juvenile Fiction,http://books.google.com/books/content?id=D1ObA...,"Violet Paz, a Chicago high school student, rel...",2005.0,3.45,304.0,1028.0,Cuba 15,"9780385732338 Violet Paz, a Chicago high schoo..."
1880,9780385732550,0385732554,The Giver,Lois Lowry,Juvenile Fiction,http://books.google.com/books/content?id=oZRlY...,"At the age of twelve, Jonas, a young boy from ...",2006.0,4.12,208.0,1464909.0,The Giver,"9780385732550 At the age of twelve, Jonas, a y..."
1881,9780385732567,0385732562,Gathering Blue,Lois Lowry,Juvenile Fiction,http://books.google.com/books/content?id=3oUhi...,"Lame and suddenly orphaned, Kira is mysterious...",2006.0,3.81,240.0,127855.0,Gathering Blue,"9780385732567 Lame and suddenly orphaned, Kira..."
1885,9780387987200,0387987207,Leaps of Faith,Nicholas Humphrey,Medical,http://books.google.com/books/content?id=V-9-I...,"""Elegant and literate"" -THE TIMES OF LONDON ""T...",1999.0,3.76,244.0,20.0,"Leaps of Faith: Science, Miracles, and the Sea...","9780387987200 ""Elegant and literate"" -THE TIME..."
1887,9780393020397,0393020398,The Annotated Huckleberry Finn,Mark Twain,Fiction,http://books.google.com/books/content?id=k5e3T...,Reproductions of the original illustrations fr...,2001.0,3.81,656.0,181.0,The Annotated Huckleberry Finn: Adventures of ...,9780393020397 Reproductions of the original il...
1905,9780393311037,0393311031,Hen's Teeth and Horse's Toes,Stephen Jay Gould,Nature,http://books.google.com/books/content?id=EPh9j...,A collection of essays answers questions about...,1994.0,4.10,416.0,1680.0,Hen's Teeth and Horse's Toes,9780393311037 A collection of essays answers q...
1906,9780393315080,0393315088,The Wanting Seed,Anthony Burgess,Fiction,http://books.google.com/books/content?id=5Aq2J...,"Tristram Foxe and his wife, Beatrice-Joanna, l...",1963.0,3.78,288.0,4701.0,The Wanting Seed,"9780393315080 Tristram Foxe and his wife, Beat..."
1907,9780393315110,0393315118,Uncommon Ground: Rethinking the Human Place in...,William Cronon,Law,http://books.google.com/books/content?id=w04mj...,"Essays by revisionist historians, scientists, ...",1996.0,4.16,560.0,649.0,Uncommon Ground: Rethinking the Human Place in...,9780393315110 Essays by revisionist historians...
1942,9780393930139,0393930130,The Norton Anthology of Literature by Women,Sandra M. Gilbert;Susan Gubar,Literary Criticism,NaN,"Long the standard teaching anthology, the land...",2007.0,4.12,1470.0,84.0,The Norton Anthology of Literature by Women: T...,9780393930139 Long the standard teaching antho...
1943,9780393959055,0393959058,"Walden ; And, Resistance to Civil Government",Henry David Thoreau,Literary Collections,http://books.google.com/books/content?id=uVxnQ...,The classic chronicle of a communion with natu...,1992.0,3.95,482.0,232.0,"Walden ; And, Resistance to Civil Government: ...",9780393959055 The classic chronicle of a commu...
2261,9780446518628,044651862X,The Celestine Prophecy,James Redfield,Fiction,http://books.google.com/books/content?id=UXolx...,You have never read a book like this before --...,1994.0,3.63,247.0,1280.0,The Celestine Prophecy: An Adventure,9780446518628 You have never read a book like ...
2409,9780451456816,0451456815,Not of Woman Born,Constance Ash;Robert A. Silverberg,Fiction,http://books.google.com/books/content?id=nOEIA...,A collection of stories that detail modern sci...,1999.0,3.80,288.0,59.0,Not of Woman Born,9780451456816 A collection of stories that det...
2410,9780451457592,0451457595,The River's Gift,Mercedes Lackey,Fiction,http://books.google.com/books/content?id=qLonv...,Fifteen-year-old Ariella spends her days in th...,1999.0,3.88,128.0,1029.0,The River's Gift,9780451457592 Fifteen-year-old Ariella spends ...
2411,9780451461636,0451461630,Thin Air,Rachel Caine,Fiction,http://books.google.com/books/content?id=kzuPo...,After Weather Warden Joanne Baldwin prevents M...,2007.0,3.96,307.0,5824.0,Thin Air,9780451461636 After Weather Warden Joanne Bald...
2412,9780451527400,0451527402,Beowulf,Burton Raffel,Fiction,http://books.google.com/books/content?id=CcMDL...,The oldest extant poem in a modern European la...,1999.0,3.43,160.0,2735.0,Beowulf: The British tradition,9780451527400 The oldest extant poem in a mode...

In [17]:
#recs = db_books.similarity_search(query, k=50)
#print(len(recs))  # how many chunks returned
#for doc in recs[:3]:
#    print(doc.page_content[:200])
#    print("---")

In [18]:
#recs = db_books.similarity_search(query, k=50)

#books_list = []
#for doc in recs:
#    lines = doc.page_content.strip('"').split("\n")
#    for line in lines:
#        line = line.strip()
#        if line:
#            try:
#                isbn = int(line.split()[0])
#                books_list.append(isbn)
#            except:
                #continue

#print(len(books_list))         # total ISBNs extracted
#print(len(set(books_list)))    # unique ISBNs

In [19]:
#print(type(books_list[0]))      # what type are the extracted ISBNs
#print(books["isbn13"].dtype)    # what dtype is the column
#print(books["isbn13"].head())   # see actual values